server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitmoa
    username: bitmoa
    password: bitmoa123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6382

logging:
  level:
    com.bitmoa: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
